### ISSUE TITLE
Inconsistent behavior when calls are registered in Python

### ISSUE THREAD

**Issue by ncorgan** [pothosware/PothosPython#21]
I'm not sure if this is an issue with the ProxyEnvironment infrastructure itself or a bug on the Python layer, but I'll put it here, since this is where I'm running into it.

When a Pothos::Proxy containing a Python block has `call()` invoked that links to a function implemented in Python, the proxy environment takes care of this and calls the Python function. This works as expected in my C++ unit tests, but when I implement `overlay()` in a Python `Pothos.Block` subclass, PothosFlow doesn't call into it. This [appears to be](https://github.com/pothosware/PothosFlow/blob/25b689b8c1790a4a89fb952206667a377920e98c/EvalEngine/BlockEval.cpp#L266) a typical proxy call, so the behavior should be the same.

This also becomes an issue with `registerProbe()`. When I register a probe called "lastValue", the signal "lastValueTriggered" and slot "probeLastValue" are created. However, when I trigger "probeLastValue", I get an error from `Pothos::Block::opaqueCall*` saying the method doesn't exist in the registry.

**Comment by guruofquality** [comment]
For the second issue I addressed this on master of PothosCore, its just a matter of simplifying the opaqueCallHandler implementation

**Comment by guruofquality** [comment]
Actually overlay function appears to be called. Unlike the probes thats not really special. Not sure whats up with that. Sure its not just a JSON typo or something?

**Comment by ncorgan** [comment]
I'll take a look. That may have been the case.

**Comment by ncorgan** [comment]
Confirmed. There was an error in my Python overlay() function. Unfortunately, PothosFlow doesn't distinguish between the overlay() function not existing and the overlay() function having an error. This may be worth a bug report itself. Since that is outside the scope of this, I'll close it.
